# Generated by Django 4.1 on 2023-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="phone",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telefono"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telefono"
            ),
        ),
    ]
