# Generated by Django 4.1 on 2023-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_historicaluser_phone_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
    ]
