# Generated by Django 4.1 on 2023-04-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("address", models.CharField(max_length=50, verbose_name="Direccion")),
                ("phone", models.BigIntegerField(verbose_name="Telefono")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("image", models.ImageField(upload_to="branches/")),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuarios registrados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.products",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo Base",
                "verbose_name_plural": "Modelos Bases",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Codigo"),
                ),
                ("image", models.ImageField(upload_to="products/")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descripción"),
                ),
                ("stock", models.IntegerField(verbose_name="Cantidad")),
                ("price", models.IntegerField(verbose_name="Precio")),
                ("brand", models.CharField(max_length=100, verbose_name="Marca")),
                (
                    "expired",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Caducidad"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.products",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.subcategory",
                        verbose_name="Sub Categoria",
                    ),
                ),
                (
                    "unite_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.measureunite",
                        verbose_name="Unidad de Medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
            },
        ),
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Eliminacion"
                    ),
                ),
                (
                    "opening_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto de Apertura",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto Actual"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hora de Apertura"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Cierre"
                    ),
                ),
                (
                    "cash_register",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo Base",
                "verbose_name_plural": "Modelos Bases",
                "abstract": False,
            },
        ),
    ]
