# Generated by Django 4.1 on 2023-04-25 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0004_alter_branch_image_alter_branch_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="employyes",
            field=models.ManyToManyField(
                related_name="branches", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
