# Generated by Django 4.1 on 2023-04-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0005_branch_employyes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="employyes",
            new_name="employees",
        ),
    ]
