# Generated by Django 4.1 on 2023-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0002_project_task_historicalproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="image",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
