# Generated by Django 4.1 on 2023-05-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0004_historicaltask"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Completado"),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="image",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="project",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Completado"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
    ]
