# Generated by Django 4.1 on 2023-05-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0005_historicalproject_is_active_project_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltask",
            old_name="state",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="state",
            new_name="is_active",
        ),
    ]
