# Generated by Django 4.1 on 2023-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0006_rename_state_historicaltask_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="image",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
